# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40624595e0163f6455c56f8f3292ff301bfa282b27c0011d4f3c777bd5253399cdcd0c474b588941219c438f72e7c63775d835a4e1359cfd44e6544fc118cb4d

test:
  secret_key_base: 142e97ffc58bb773d3a3043b396df7afb7566d5f5e63f0046faab8bee4274ecc7ddf12454fd7982388c7cce672405022e1befd71a7fa015033df628d30166a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
